py_test(
    name = "test_provable_repair",
    size = "small",
    srcs = ["test_provable_repair.py"],
    deps = [
        "//prdnn:provable_repair",
        "@bazel_python//:pytest_helper",
    ],
)

py_test(
    name = "test_ft_repair",
    size = "small",
    srcs = ["test_ft_repair.py"],
    deps = [
        "//prdnn:ft_repair",
        "@bazel_python//:pytest_helper",
    ],
)

py_test(
    name = "test_ddnn",
    size = "small",
    srcs = ["test_ddnn.py"],
    deps = [
        "//prdnn:ddnn",
        "@bazel_python//:pytest_helper",
    ],
)
